### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by putsi** [JanoCodes/Ticketing#19]
#### Describe the bug
I'm having trouble starting the app with the provided Dockerfile.

#### To Reproduce
1. Clone the repository.
2. Run "docker build ."
3. Run "docker run id_of_image"
4. See Mariadb complaining about running with root-user.

#### Expected behavior:
Expecting the ticketing-app to start.

#### Desktop:
 - Docker 18.06.1-ce
- Ticketing commit bfa5c3a4d13ecf5cf3466308095f914d71da245e

**Comment by andrewying** [comment]
Hiya! 

Thanks for reporting the issue. Given that Docker support can be helpful for particularly white-hat researchers, I have decided to officially support Docker and have made some changes to the previously non-functioning Dockerfile.

Hopefully everything should be working now!

- Andrew

**Comment by putsi** [comment]
Hey!

I'm getting the following when running `docker build .` on the new Dockerfile:
```
Step 15/18 : RUN cd /var/www/jano;     bash -c "mysqld --user=mysql &";     sleep 10;     php jano migrate --seed --force
 ---> Running in 7ee0136d00e8
2018-12-13  0:03:09 139843908406400 [Note] mysqld (mysqld 10.1.34-MariaDB-0ubuntu0.18.04.1) starting as process 9 ...

In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [1698] Access denied for user 'forge'@'localhost' (SQL: sel  
  ect * from information_schema.tables where table_schema = forge and table_n  
  ame = migrations)                                                            
                                                                               

In Connector.php line 67:
                                                                     
  SQLSTATE[HY000] [1698] Access denied for user 'forge'@'localhost'  
```
