### ISSUE TITLE
Errors in Connection.php

### ISSUE THREAD

**Issue by sawzeeyy** [JanoCodes/Ticketing#49]
#### Describe the bug
I followed the steps in README but at the last step, I got an error.

```
> php jano migrate

In Connection.php line 664:

  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s
  chema.tables where table_schema = jano and table_name = migrations)


In Connector.php line 67:

  SQLSTATE[HY000] [2002] Connection refused
```

#### Screenshots
<img width="565" alt="screen shot 2018-12-31 at 6 35 26 am" src="https://user-images.githubusercontent.com/32202226/50555035-9555d900-0cc6-11e9-9136-859a43b12d92.png">

#### Desktop (please complete the following information):
-  OS: OSX

**Comment by andrewying** [comment]
Sorry if that's not clear - but do you have a MySQL/MariaDB server set up? Jano Ticketing System requires a MySQL database to run!

**Comment by sawzeeyy** [comment]
Hi @andrewying,

No, I don't have one but I have Xampp installed. Please guide me on how to proceed from here.
